version: "3"

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: always
    ports:
      - "3000:3000"
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"
  db:
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rum2go:1.0-db
    volumes:
      - ./database/db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
