version: "3"
services:
  db:
    container_name: rum2go_db
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rum2go:1.0-db
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
