export const MEALS_ADD_SUCCESS = 'MEALS_ADD_SUCCESS';
export const MEALS_ADD_ERROR = 'MEALS_ADD_ERROR';
export const MEALS_REMOVE_SUCCESS = 'MEALS_REMOVE_SUCCESS';
export const MEALS_REMOVE_ERROR = 'MEALS_REMOVE_ERROR';
export const MEALS_UPDATE_SUCCESS = 'MEALS_UPDATE_SUCCESS';
export const MEALS_UPDATE_ERROR = 'MEALS_UPDATE_ERROR';
export const MEALS_GET_SUCCESS = 'MEALS_GET_SUCCESS';
export const MEALS_GET_ERROR = 'MEALS_GET_ERROR';